[package]
name = "cure-java-parser"
description = "Fault-tolerant Java source parser producing cure-java-ast"
version.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
keywords = ["java", "parser", "fault-tolerant"]
categories = ["parser-implementations"]

[dependencies]
cure-engine = { workspace = true }
cure-java-ast = { workspace = true }

[dev-dependencies]
cure-java-print = { workspace = true }
