[package]
name = "cure-java-simplify"
description = "Java simplification rules and facade over cure-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
keywords = ["java", "deobfuscation", "simplification"]
categories = ["development-tools"]

[dependencies]
cure-engine = { workspace = true }
cure-java-ast = { workspace = true }

[dev-dependencies]
cure-java-print = { workspace = true }
cure-java-parser = { workspace = true }
