[package]
name = "cure-java-simplify"
description = "Java simplification rules and facade over cure-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cure-engine = { path = "../cure-engine" }
cure-java-ast = { path = "../cure-java-ast" }

[dev-dependencies]
cure-java-print = { path = "../cure-java-print" }
cure-java-parser = { path = "../cure-java-parser" }
